// <auto-generated />
using System;
using System.Text.Json;
using DandDSoft.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestorHerores.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260205163236_MigracionInicial")]
    partial class MigracionInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("gestorHeroes")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GestorHeroes.Models.Personaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Gremio")
                        .HasColumnType("text");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<JsonDocument>("Rasgos")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("Personajes", "gestorHeroes");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("GestorHeroes.Models.Arquero", b =>
                {
                    b.HasBaseType("GestorHeroes.Models.Personaje");

                    b.Property<double>("Precision")
                        .HasColumnType("double precision");

                    b.Property<bool>("TieneMascota")
                        .HasColumnType("boolean");

                    b.ToTable("Arqueros", "gestorHeroes");
                });

            modelBuilder.Entity("GestorHeroes.Models.Clerigo", b =>
                {
                    b.HasBaseType("GestorHeroes.Models.Personaje");

                    b.Property<string>("Deidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PuntosSanacion")
                        .HasColumnType("integer");

                    b.ToTable("Clerigos", "gestorHeroes");
                });

            modelBuilder.Entity("GestorHeroes.Models.Guerrero", b =>
                {
                    b.HasBaseType("GestorHeroes.Models.Personaje");

                    b.Property<string>("ArmaPrincipal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Furia")
                        .HasColumnType("integer");

                    b.ToTable("Guerreros", "gestorHeroes");
                });

            modelBuilder.Entity("Mago", b =>
                {
                    b.HasBaseType("GestorHeroes.Models.Personaje");

                    b.Property<string>("ElementoPrincipal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Mana")
                        .HasColumnType("integer");

                    b.ToTable("Magos", "gestorHeroes");
                });

            modelBuilder.Entity("GestorHeroes.Models.Arquero", b =>
                {
                    b.HasOne("GestorHeroes.Models.Personaje", null)
                        .WithOne()
                        .HasForeignKey("GestorHeroes.Models.Arquero", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GestorHeroes.Models.Clerigo", b =>
                {
                    b.HasOne("GestorHeroes.Models.Personaje", null)
                        .WithOne()
                        .HasForeignKey("GestorHeroes.Models.Clerigo", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GestorHeroes.Models.Guerrero", b =>
                {
                    b.HasOne("GestorHeroes.Models.Personaje", null)
                        .WithOne()
                        .HasForeignKey("GestorHeroes.Models.Guerrero", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mago", b =>
                {
                    b.HasOne("GestorHeroes.Models.Personaje", null)
                        .WithOne()
                        .HasForeignKey("Mago", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
